### ISSUE TITLE
Quick Question?

### ISSUE THREAD

**Issue by Mentors4EDU** [Ideamarket/ideamarket-contracts#3]
Hi, I wasn't sure where to post this in regards to the ideamarket code + design. 

Anyways, I really like the concept, but have primarily one question?

If somebody's social media account was deleted or censored in the future, what happens to the value of their token on ideamarket? If it has a reliance on centralized social networks in regards to actual value, then is it really decentralized by design?

This is just the one thing I am trying to understand in regards to insight

**Comment by Mentors4EDU** [comment]
BTW: If you can get past that one point, then this is a really solid concept. The network seems really well built interface-wise along w/ lots of the primary execution. My main concern is reputation or token value being tied to accounts on centralized networks and how an issue like that may be tackled?

**Comment by Shmoji** [comment]
This is a good question to ask in the Ideamarket Discord: https://discord.com/invite/zaXZXGE4Ke
